Feature/get by admin
Proko-Tech/PIT-Proko-Internal-Tool pull request #11
Opened 2021-07-08 00:41 UTC by Eldar827

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- get parking lot information using the admin id

## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
feature/get_by_adminId

| [TODO Screenshot Link] |
![Screen Shot 2021-07-07 at 5 41 14 PM](https://user-images.githubusercontent.com/53462516/124844966-882a9c80-df4a-11eb-8c9e-1d71430a5028.png)

2021-07-08 02:00 UTC, YuyusanK requested changes

2021-07-08 02:00 UTC, YuyusanK commented on routes/index.js
> +  const a = await lotsModel.getByAdminID('1');
Remove this line

2021-07-08 07:12 UTC, YuyusanK requested changes

2021-07-08 07:12 UTC, YuyusanK commented on database/model/lotModel.js
> +            .join('lots','lot_ownerships.id','=','lots.id')
`lot_ownerships.id` should be `lot_ownerships.lot_id`.

2021-07-09 02:13 UTC, anguyen698 requested changes
Delete the extra spaces after the "await" and "return" in getByAdminId function, and change lotsModel to lot_model in index.js

2021-07-09 21:36 UTC, closed without merging