Feature/new parking lot page
Proko-Tech/PIT-Proko-Internal-Tool pull request #20
Opened 2021-07-16 21:14 UTC by anguyen698

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- Fixed navbar css
- Moved external css to separate file
- Deleted debugging statements

## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Fixed navbar
![navbar-css-fix](https://user-images.githubusercontent.com/63482191/126009085-49345984-28ed-4a5f-8240-3d8257b4f8e9.PNG)

2021-07-16 21:46 UTC, Eldar827 approved these changes
lgtm

2021-07-17 02:42 UTC, YuyusanK requested changes

2021-07-17 02:42 UTC, YuyusanK commented on views/component/pageTitle.ejs
>      .nav-wrapper {
Please move this to `page_title_style.css` in the styles folders

2021-07-20 01:48 UTC, samuelng678 approved these changes

2021-07-20 20:22 UTC, YuyusanK approved these changes
lgtm

2021-07-20 20:22 UTC, merged