Added adminAccountsModel
Proko-Tech/PIT-Proko-Internal-Tool pull request #22
Opened 2021-07-17 00:45 UTC by anguyen698

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- Added adminAccountsModel

## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

adminAccountsModel code
![admin-account-model](https://user-images.githubusercontent.com/63482191/126020342-4ea50f32-f5d1-4d7f-ae91-b08e3544a026.PNG)

2021-07-20 20:21 UTC, YuyusanK requested changes
lgtm

2021-07-20 20:21 UTC, YuyusanK commented on database/model/adminAccountsModel.js
> +        .get();
.get() is not a knex function, please take a look at .select() in knex.

2021-07-21 02:00 UTC, Eldar827 approved these changes
lgtm

2021-07-21 02:45 UTC, YuyusanK approved these changes
lgtm

2021-07-21 03:31 UTC, merged