Feature/spot hash
Proko-Tech/PIT-Proko-Internal-Tool pull request #23
Opened 2021-07-22 23:35 UTC by anguyen698

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- Added insertSpotHash()
- Added update() to lotModel
- Added route for update()

## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

insertSpotHash code
![insert-spot](https://user-images.githubusercontent.com/63482191/126721548-d7293c0f-c1f4-4d9a-bf0f-5440f4fc9b38.PNG)

update code
![update-func](https://user-images.githubusercontent.com/63482191/126721632-5fe3acc2-fe27-41bd-87b7-96a55b94174f.PNG)

![update-route](https://user-images.githubusercontent.com/63482191/126721640-68d0808e-6ac4-4bdc-991c-f31c019dd8be.PNG)

2021-07-23 01:56 UTC, Eldar827 approved these changes
lgtm

2021-07-26 20:18 UTC, samuelng678 approved these changes
lgtm

2021-07-27 00:03 UTC, YuyusanK requested changes

2021-07-27 00:03 UTC, YuyusanK commented on database/model/spotsModel.js
> +            .insert(spot_hash);
change insert to update based off of id.

2021-07-27 01:14 UTC, YuyusanK requested changes

2021-07-27 01:14 UTC, YuyusanK commented on database/model/lotModel.js
> +        .update({ changes });
`changes` is going to be passed through as a json. Please take out `{ }`.

2021-07-27 23:37 UTC, YuyusanK requested changes

2021-07-27 23:37 UTC, YuyusanK commented on database/model/lotModel.js
> +    const [result] = await db('lots')
please take this out. `const [result] =`

2021-07-27 23:37 UTC, YuyusanK commented on database/model/lotModel.js
> +    const [result] = await db('lots')
the whole update function should be in a try-catch

2021-07-29 02:16 UTC, YuyusanK requested changes

2021-07-29 02:16 UTC, YuyusanK commented on database/model/spotsModel.js
> + * insert spot hash using the information given to us
description is not correct

2021-07-29 02:16 UTC, YuyusanK commented on database/model/spotsModel.js
> +            .where(spot_id)
use `{ }` to create a json for `spot_id`

2021-07-29 21:29 UTC, YuyusanK requested changes

2021-07-29 21:29 UTC, YuyusanK commented on routes/parking_lot.js
> +            res.status(200).json({updated: result})
`updated` should be `message`

2021-08-03 01:41 UTC, YuyusanK approved these changes

2021-08-03 01:41 UTC, merged