feature/create
Proko-Tech/PIT-Proko-Internal-Tool pull request #24
Opened 2021-07-23 20:48 UTC by Eldar827

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- create()
- create spotModel.js

## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- | create()
| [TODO Screenshot Link] |
![Screen Shot 2021-07-23 at 1 47 51 PM](https://user-images.githubusercontent.com/53462516/126839866-48a2651f-e32b-4f10-aa78-b0b0c4631632.png)

2021-07-27 01:50 UTC, YuyusanK approved these changes

2021-07-27 01:51 UTC, anguyen698 approved these changes
lgtm

2021-07-27 01:53 UTC, YuyusanK requested changes

2021-07-27 01:53 UTC, YuyusanK commented on database/model/spotsModel.js
> +async function create(lot_id){
this function will pass through more than `lot_id` this should be `spots_info`

2021-07-27 01:53 UTC, YuyusanK commented on database/model/spotsModel.js
> +            .insert([{lot_id : lot_id}]);
`insert()` should insert `spots_info`

2021-07-29 21:15 UTC, YuyusanK approved these changes

2021-07-29 22:19 UTC, samuelng678 approved these changes

2021-07-29 22:28 UTC, merged