Feature/new parking lot page
Proko-Tech/PIT-Proko-Internal-Tool pull request #29
Opened 2021-08-16 19:24 UTC by anguyen698

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- Added comments to CSS
- Made spots portion of new parking lot page dynamic

## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Focusin
![total-spots-focusin](https://user-images.githubusercontent.com/63482191/129618479-dffcd267-dd25-45b4-89af-c366d61085a4.PNG)

Focusout/Enter press
![total-spots-focusout](https://user-images.githubusercontent.com/63482191/129618516-68a4d57a-fe8d-4334-9dc9-b8f330c7d967.PNG)

2021-08-17 03:19 UTC, YuyusanK requested changes

2021-08-17 03:19 UTC, YuyusanK commented on views/component/parkingLots/parkingLotInfoCard.ejs
> +$( "#total-spots-input" )
please put the scripts into a scripts file.

2021-08-19 02:20 UTC, samuelng678 approved these changes

2021-08-19 02:20 UTC, YuyusanK requested changes

2021-08-19 02:20 UTC, YuyusanK commented on public/javascript/spotsInputField.js
> +    var num_spots = $( "#total-spots" ).val();
please use const instead of var

2021-08-20 02:07 UTC, YuyusanK requested changes

2021-08-20 02:07 UTC, YuyusanK commented on views/component/parkingLots/parkingLotInfoCard.ejs
>                              <input id="price" placeholder="Price/Hr (default)" type="text" class="validate">
Take a look at `login.ejs` under the `login` folder in `page`. If you look at the input portion of the page, you will see that one of the attributes in the input element is `name`. `name` is what allows the front end to pass through information into the backend. You need to add the attribute `name` into each input field in this form. 
https://www.w3schools.com/tags/att_name.asp
Please use this as reference and let me know if you have any questions.

2021-08-21 03:14 UTC, YuyusanK requested changes

2021-08-21 03:21 UTC, YuyusanK approved these changes

2021-08-21 03:21 UTC, merged