Feature/v2/sensor update UI
Proko-Tech/PIT-Proko-Internal-Tool pull request #53
Opened 2022-07-10 05:09 UTC by hage1005

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- closing #52 
- 
## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2022-07-10 05:58 UTC, mingkaili requested changes
TL;DR:
1. Break down the feature to submit smaller PRs. Right now what we have here is a cluster of work without enough quality.
2. Read design docs thoroughly.
3. Read over the PR before requesting for reviews as there are lots of development specific things like console logs, comments that isn't needed in production.

This is an extremely big PR with 40 file changes and 6000 lines of changes. You have done the following things in this PR:
- Your linter or IDE probably automatically did a codebase wide refactor that inserted a bunch of whitespaces and a bunch of indentations. If you are going to do that, make a new branch called refactor and do it there bc these things are extremely misleading and takes spaces for reviewers to focus on the actual changes
- Full Frontend changes
- Inserted new routes
- Made new Model functions

The above 4 things can be separated to at least 4 different PRs for readability enhancement.

**Keep In Mind** You always want to submit small size PRs in the industry due to: 
1. Small PRs gets faster code reviews
4. Small PRs get better reviews with a smaller size
5. Small PRs SIGNIFICANTLY improve code quality(You did not read over your code change bc you have lots of left over console log statements, and unneeded comments that makes the PR dirty).
6. Small PRs help protect the flow
There are many more reasons you can refer to [this simple article](https://www.swarmia.com/blog/why-small-pull-requests-are-better/) for the benefits

I only reviewed the backend portion of your PR and due to it's size, and it was a quick skim through. You need to read over the PR before asking for review to remove some of the quick things like: unneeded comments, console logs statements, etc.

2022-07-10 05:58 UTC, mingkaili commented on .vscode/launch.json
> +{
remove IDE specific file, add ignore for all .vscode files in .gitignore

2022-07-10 05:58 UTC, mingkaili commented on database/model/lotModel.js
> +            console.log("Im here 1");
remove debug logs

2022-07-10 05:58 UTC, mingkaili commented on database/model/spotsModel.js
> +    console.log("spot_hashes", spot_hashes);
remove debug logs

2022-07-10 05:58 UTC, mingkaili commented on database/model/spotsModel.js
> +    console.log("spot_info", spot_info);
remove debug logs

2022-07-10 05:58 UTC, mingkaili commented on database/model/spotsModel.js
> +    // Update the spots with the given spot_hashes
Remove unneeded comments

2022-07-10 05:58 UTC, mingkaili commented on database/model/spotsModel.js
> +            console.log("Hash: " + spot_hashes);
ditto

2022-07-10 05:58 UTC, mingkaili commented on database/model/spotsModel.js
> +            console.log(spot_info);
ditto

2022-07-10 05:58 UTC, mingkaili commented on database/model/spotsModel.js
> +    // try {
ditto

2022-07-10 05:58 UTC, mingkaili commented on routes/firmware.js
> +var express = require('express');
const

2022-07-10 05:58 UTC, mingkaili commented on routes/firmware.js
> +var router = express.Router();
ditto

2022-07-10 05:58 UTC, mingkaili commented on routes/firmware.js
> +        res.send(err)
nit: instead of using send. use a status code instead: 500

2022-07-10 05:58 UTC, mingkaili commented on routes/firmware.js
> +        if (await firmwareVersionModel.exists(req.body.version)) {
Bad structure: never put functions in the condition of if statements.

```
const firmwareVersions = firmwareVersionModel.getByVersion(req.body.version);
const isFirmwareExists = firmwareVersions.length !== 0;
if (!isFirmwareExists) {
  blah blah
}
```

2022-07-10 05:58 UTC, mingkaili commented on routes/firmware.js
> +            return res.send('Version already exists');
status code: 401 or 409

2022-07-10 05:58 UTC, mingkaili commented on routes/firmware.js
> +            return res.send('All fields are required');
status code: 400

2022-07-10 05:58 UTC, mingkaili commented on routes/firmware.js
> +        return res.redirect(data[0].ESP8266_url);
if you are going to user return, make sure you return on every res operation to keep them consistent.

2022-07-10 05:58 UTC, mingkaili commented on routes/firmware.js
> +router.get('/download/ESP32/:version', async function (req, res, next) {
You are writing this route in the wrong place. There is a separate repository that already have those routes. This is why it's important to read the documentation and have a clear documentation instead of doing this too quickly.

2022-07-10 05:58 UTC, mingkaili commented on routes/index.js
> +const spotsModel = require('../database/model/spotsModel');
why adding this?

2022-07-10 18:43 UTC, mingkaili commented
The lint PR was merged. Make sure to rebase this branch.

2022-07-10 23:39 UTC, hage1005 commented on routes/firmware.js
> +router.get('/download/ESP32/:version', async function (req, res, next) {
Do you refer to the sensor-version-control repo?

2022-08-08 22:06 UTC, mingkaili commented
We can close this PR now right?

2022-08-10 23:52 UTC, closed without merging