Feature/parking lot route
Proko-Tech/PIT-Proko-Internal-Tool pull request #7
Opened 2021-07-02 22:47 UTC by anguyen698

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
- Added GET /parking_lot route
- Used get() to retrieve parking_lot info

## Checklist

Remove any items which are not applicable.

- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Code change and  localhost:3000 working |
| --- |
| ![get-parking-lot-screenshot](https://user-images.githubusercontent.com/63482191/124334661-a8261e80-db4c-11eb-9632-bea28027a76d.PNG)|

2021-07-03 00:03 UTC, Eldar827 approved these changes
lgtm

2021-07-03 00:06 UTC, samuelng678 approved these changes
lgtm

2021-07-03 02:24 UTC, YuyusanK commented on routes/parking_lot.js
>  const Lots = require("../database/model/lotModel");
Lots should be named lot_model

2021-07-03 02:24 UTC, YuyusanK commented on routes/parking_lot.js
> +    Lots.get();
Save the returned values in a variable.

2021-07-03 02:25 UTC, YuyusanK requested changes
Please fix those sections

2021-07-06 20:00 UTC, YuyusanK approved these changes
lgtm

2021-07-06 21:02 UTC, merged