Feature/post parking lot route
Proko-Tech/PIT-Proko-Internal-Tool pull request #9
Opened 2021-07-06 20:08 UTC by samuelng678

# Administrative Info
Make sure your branch name conforms to: `feature/hotfix/.../describe_your_branch_with_underscores

### Changes
What changes did you make?
Implemented POST function in parking_lot.js
## Checklist

Remove any items which are not applicable.

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tested my program thoroughly
- [ ] Did you add/sub fields in the environment file? if so please update .env_sample

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
![Screen Shot 2021-07-06 at 13 08 02](https://user-images.githubusercontent.com/56614355/124660553-33f4bf00-de5b-11eb-8e48-65665e2a30a6.png)

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2021-07-06 22:59 UTC, anguyen698 requested changes
Change Lots to lot_model

2021-07-06 23:59 UTC, Eldar827 approved these changes
lgtm

2021-07-07 01:49 UTC, YuyusanK requested changes
Looks good, but I'm sure if you pulled from master before making the PR. Please pull from the master before making the PR.

2021-07-07 02:11 UTC, YuyusanK requested changes

2021-07-07 02:11 UTC, YuyusanK commented on routes/parking_lot.js
>  router.post("/parking_lot", (req, res) => {
This is an async function. Please add `async function` before `(req, res)`. Please remove `=>`

2021-07-07 02:11 UTC, YuyusanK commented on routes/parking_lot.js
> +      lot_model.insert(req.body);
Please add `await` before `lot_model`

2021-07-07 02:30 UTC, closed without merging